#!/bin/bash
### BEGIN INIT INFO
# Provides:             dht22Service
# Required-Start:       $local_fs mongodb pigpiod
# X-UnitedLinux-Should-Start:
# Required-Stop:        $local_fs
# X-UnitedLinux-Should-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Reads DHT22 sensor and stores information in mongo.
### END INIT INFO

case "$1" in
        start)
                su - pi -c "/usr/bin/python /apps/dht22Service/dht22Service.py &"
                ;;
        stop)
                pid=`ps -ef | grep '[p]ython /apps/dht22Service/dht22Service.py' | awk '{ print $2 }'`
                kill $pid
                ;;
        restart)
                stop
                start
                ;;
esac
